//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINKERS.WCFSnikers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/WCFSnikers")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int objetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precio_compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_productoField, value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int objetivo {
            get {
                return this.objetivoField;
            }
            set {
                if ((this.objetivoField.Equals(value) != true)) {
                    this.objetivoField = value;
                    this.RaisePropertyChanged("objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio_compra {
            get {
                return this.precio_compraField;
            }
            set {
                if ((this.precio_compraField.Equals(value) != true)) {
                    this.precio_compraField = value;
                    this.RaisePropertyChanged("precio_compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFSnikers")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_postalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coloniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo_postal {
            get {
                return this.codigo_postalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_postalField, value) != true)) {
                    this.codigo_postalField = value;
                    this.RaisePropertyChanged("codigo_postal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                if ((object.ReferenceEquals(this.coloniaField, value) != true)) {
                    this.coloniaField = value;
                    this.RaisePropertyChanged("colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/WCFSnikers")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costo_envioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccion_entregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int costo_envio {
            get {
                return this.costo_envioField;
            }
            set {
                if ((this.costo_envioField.Equals(value) != true)) {
                    this.costo_envioField = value;
                    this.RaisePropertyChanged("costo_envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion_entrega {
            get {
                return this.direccion_entregaField;
            }
            set {
                if ((object.ReferenceEquals(this.direccion_entregaField, value) != true)) {
                    this.direccion_entregaField = value;
                    this.RaisePropertyChanged("direccion_entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compra {
            get {
                return this.id_compraField;
            }
            set {
                if ((this.id_compraField.Equals(value) != true)) {
                    this.id_compraField = value;
                    this.RaisePropertyChanged("id_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precioTotal {
            get {
                return this.precioTotalField;
            }
            set {
                if ((this.precioTotalField.Equals(value) != true)) {
                    this.precioTotalField = value;
                    this.RaisePropertyChanged("precioTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCompra", Namespace="http://schemas.datacontract.org/2004/07/WCFSnikers")]
    [System.SerializableAttribute()]
    public partial class DetalleCompra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compra {
            get {
                return this.id_compraField;
            }
            set {
                if ((this.id_compraField.Equals(value) != true)) {
                    this.id_compraField = value;
                    this.RaisePropertyChanged("id_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_productoField, value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSnikers.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        SINKERS.WCFSnikers.Productos[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnikers.Productos[]> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusqueda", ReplyAction="http://tempuri.org/IService1/GetBusquedaResponse")]
        SINKERS.WCFSnikers.Productos[] GetBusqueda(int objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusqueda", ReplyAction="http://tempuri.org/IService1/GetBusquedaResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnikers.Productos[]> GetBusquedaAsync(int objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCliente", ReplyAction="http://tempuri.org/IService1/SetClienteResponse")]
        int SetCliente(SINKERS.WCFSnikers.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCliente", ReplyAction="http://tempuri.org/IService1/SetClienteResponse")]
        System.Threading.Tasks.Task<int> SetClienteAsync(SINKERS.WCFSnikers.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCompra", ReplyAction="http://tempuri.org/IService1/SetCompraResponse")]
        int SetCompra(SINKERS.WCFSnikers.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCompra", ReplyAction="http://tempuri.org/IService1/SetCompraResponse")]
        System.Threading.Tasks.Task<int> SetCompraAsync(SINKERS.WCFSnikers.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetDetalleCompra", ReplyAction="http://tempuri.org/IService1/SetDetalleCompraResponse")]
        int SetDetalleCompra(SINKERS.WCFSnikers.DetalleCompra detalle_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetDetalleCompra", ReplyAction="http://tempuri.org/IService1/SetDetalleCompraResponse")]
        System.Threading.Tasks.Task<int> SetDetalleCompraAsync(SINKERS.WCFSnikers.DetalleCompra detalle_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarLogin", ReplyAction="http://tempuri.org/IService1/VerificarLoginResponse")]
        int VerificarLogin(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarLogin", ReplyAction="http://tempuri.org/IService1/VerificarLoginResponse")]
        System.Threading.Tasks.Task<int> VerificarLoginAsync(string correo, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SINKERS.WCFSnikers.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SINKERS.WCFSnikers.IService1>, SINKERS.WCFSnikers.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SINKERS.WCFSnikers.Productos[] GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnikers.Productos[]> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
        
        public SINKERS.WCFSnikers.Productos[] GetBusqueda(int objetivo) {
            return base.Channel.GetBusqueda(objetivo);
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnikers.Productos[]> GetBusquedaAsync(int objetivo) {
            return base.Channel.GetBusquedaAsync(objetivo);
        }
        
        public int SetCliente(SINKERS.WCFSnikers.Cliente cliente) {
            return base.Channel.SetCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> SetClienteAsync(SINKERS.WCFSnikers.Cliente cliente) {
            return base.Channel.SetClienteAsync(cliente);
        }
        
        public int SetCompra(SINKERS.WCFSnikers.Compra compra) {
            return base.Channel.SetCompra(compra);
        }
        
        public System.Threading.Tasks.Task<int> SetCompraAsync(SINKERS.WCFSnikers.Compra compra) {
            return base.Channel.SetCompraAsync(compra);
        }
        
        public int SetDetalleCompra(SINKERS.WCFSnikers.DetalleCompra detalle_compra) {
            return base.Channel.SetDetalleCompra(detalle_compra);
        }
        
        public System.Threading.Tasks.Task<int> SetDetalleCompraAsync(SINKERS.WCFSnikers.DetalleCompra detalle_compra) {
            return base.Channel.SetDetalleCompraAsync(detalle_compra);
        }
        
        public int VerificarLogin(string correo, string contrasena) {
            return base.Channel.VerificarLogin(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<int> VerificarLoginAsync(string correo, string contrasena) {
            return base.Channel.VerificarLoginAsync(correo, contrasena);
        }
    }
}
