//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINKERS.WCFSnickers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/PRUEBA1")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Precio_compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_productoField, value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Objetivo {
            get {
                return this.ObjetivoField;
            }
            set {
                if ((this.ObjetivoField.Equals(value) != true)) {
                    this.ObjetivoField = value;
                    this.RaisePropertyChanged("Objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio_compra {
            get {
                return this.Precio_compraField;
            }
            set {
                if ((this.Precio_compraField.Equals(value) != true)) {
                    this.Precio_compraField = value;
                    this.RaisePropertyChanged("Precio_compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/PRUEBA1")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_postalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_postal {
            get {
                return this.Codigo_postalField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_postalField, value) != true)) {
                    this.Codigo_postalField = value;
                    this.RaisePropertyChanged("Codigo_postal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_cliente {
            get {
                return this.Id_clienteField;
            }
            set {
                if ((this.Id_clienteField.Equals(value) != true)) {
                    this.Id_clienteField = value;
                    this.RaisePropertyChanged("Id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/PRUEBA1")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Costo_envioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_entregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Costo_envio {
            get {
                return this.Costo_envioField;
            }
            set {
                if ((this.Costo_envioField.Equals(value) != true)) {
                    this.Costo_envioField = value;
                    this.RaisePropertyChanged("Costo_envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_entrega {
            get {
                return this.Direccion_entregaField;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_entregaField, value) != true)) {
                    this.Direccion_entregaField = value;
                    this.RaisePropertyChanged("Direccion_entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_cliente {
            get {
                return this.Id_clienteField;
            }
            set {
                if ((this.Id_clienteField.Equals(value) != true)) {
                    this.Id_clienteField = value;
                    this.RaisePropertyChanged("Id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_compra {
            get {
                return this.Id_compraField;
            }
            set {
                if ((this.Id_compraField.Equals(value) != true)) {
                    this.Id_compraField = value;
                    this.RaisePropertyChanged("Id_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrecioTotal {
            get {
                return this.PrecioTotalField;
            }
            set {
                if ((this.PrecioTotalField.Equals(value) != true)) {
                    this.PrecioTotalField = value;
                    this.RaisePropertyChanged("PrecioTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCompra", Namespace="http://schemas.datacontract.org/2004/07/PRUEBA1")]
    [System.SerializableAttribute()]
    public partial class DetalleCompra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_compra {
            get {
                return this.Id_compraField;
            }
            set {
                if ((this.Id_compraField.Equals(value) != true)) {
                    this.Id_compraField = value;
                    this.RaisePropertyChanged("Id_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_productoField, value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFSnickers.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        SINKERS.WCFSnickers.Productos[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusqueda", ReplyAction="http://tempuri.org/IService1/GetBusquedaResponse")]
        SINKERS.WCFSnickers.Productos[] GetBusqueda(int objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusqueda", ReplyAction="http://tempuri.org/IService1/GetBusquedaResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaAsync(int objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCliente", ReplyAction="http://tempuri.org/IService1/SetClienteResponse")]
        int SetCliente(SINKERS.WCFSnickers.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCliente", ReplyAction="http://tempuri.org/IService1/SetClienteResponse")]
        System.Threading.Tasks.Task<int> SetClienteAsync(SINKERS.WCFSnickers.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        SINKERS.WCFSnickers.Cliente[] GetClientes(string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnickers.Cliente[]> GetClientesAsync(string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCompra", ReplyAction="http://tempuri.org/IService1/SetCompraResponse")]
        int SetCompra(SINKERS.WCFSnickers.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCompra", ReplyAction="http://tempuri.org/IService1/SetCompraResponse")]
        System.Threading.Tasks.Task<int> SetCompraAsync(SINKERS.WCFSnickers.Compra compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetDetalleCompra", ReplyAction="http://tempuri.org/IService1/SetDetalleCompraResponse")]
        int SetDetalleCompra(SINKERS.WCFSnickers.DetalleCompra detalle_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetDetalleCompra", ReplyAction="http://tempuri.org/IService1/SetDetalleCompraResponse")]
        System.Threading.Tasks.Task<int> SetDetalleCompraAsync(SINKERS.WCFSnickers.DetalleCompra detalle_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarLogin", ReplyAction="http://tempuri.org/IService1/VerificarLoginResponse")]
        int VerificarLogin(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarLogin", ReplyAction="http://tempuri.org/IService1/VerificarLoginResponse")]
        System.Threading.Tasks.Task<int> VerificarLoginAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusquedaMarcaModelo", ReplyAction="http://tempuri.org/IService1/GetBusquedaMarcaModeloResponse")]
        SINKERS.WCFSnickers.Productos[] GetBusquedaMarcaModelo(string objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusquedaMarcaModelo", ReplyAction="http://tempuri.org/IService1/GetBusquedaMarcaModeloResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaMarcaModeloAsync(string objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusquedaClave", ReplyAction="http://tempuri.org/IService1/GetBusquedaClaveResponse")]
        SINKERS.WCFSnickers.Productos[] GetBusquedaClave(string objetivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusquedaClave", ReplyAction="http://tempuri.org/IService1/GetBusquedaClaveResponse")]
        System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaClaveAsync(string objetivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SINKERS.WCFSnickers.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SINKERS.WCFSnickers.IService1>, SINKERS.WCFSnickers.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SINKERS.WCFSnickers.Productos[] GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
        
        public SINKERS.WCFSnickers.Productos[] GetBusqueda(int objetivo) {
            return base.Channel.GetBusqueda(objetivo);
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaAsync(int objetivo) {
            return base.Channel.GetBusquedaAsync(objetivo);
        }
        
        public int SetCliente(SINKERS.WCFSnickers.Cliente cliente) {
            return base.Channel.SetCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> SetClienteAsync(SINKERS.WCFSnickers.Cliente cliente) {
            return base.Channel.SetClienteAsync(cliente);
        }
        
        public SINKERS.WCFSnickers.Cliente[] GetClientes(string clave) {
            return base.Channel.GetClientes(clave);
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnickers.Cliente[]> GetClientesAsync(string clave) {
            return base.Channel.GetClientesAsync(clave);
        }
        
        public int SetCompra(SINKERS.WCFSnickers.Compra compra) {
            return base.Channel.SetCompra(compra);
        }
        
        public System.Threading.Tasks.Task<int> SetCompraAsync(SINKERS.WCFSnickers.Compra compra) {
            return base.Channel.SetCompraAsync(compra);
        }
        
        public int SetDetalleCompra(SINKERS.WCFSnickers.DetalleCompra detalle_compra) {
            return base.Channel.SetDetalleCompra(detalle_compra);
        }
        
        public System.Threading.Tasks.Task<int> SetDetalleCompraAsync(SINKERS.WCFSnickers.DetalleCompra detalle_compra) {
            return base.Channel.SetDetalleCompraAsync(detalle_compra);
        }
        
        public int VerificarLogin(string correo, string contrasena) {
            return base.Channel.VerificarLogin(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<int> VerificarLoginAsync(string correo, string contrasena) {
            return base.Channel.VerificarLoginAsync(correo, contrasena);
        }
        
        public SINKERS.WCFSnickers.Productos[] GetBusquedaMarcaModelo(string objetivo) {
            return base.Channel.GetBusquedaMarcaModelo(objetivo);
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaMarcaModeloAsync(string objetivo) {
            return base.Channel.GetBusquedaMarcaModeloAsync(objetivo);
        }
        
        public SINKERS.WCFSnickers.Productos[] GetBusquedaClave(string objetivo) {
            return base.Channel.GetBusquedaClave(objetivo);
        }
        
        public System.Threading.Tasks.Task<SINKERS.WCFSnickers.Productos[]> GetBusquedaClaveAsync(string objetivo) {
            return base.Channel.GetBusquedaClaveAsync(objetivo);
        }
    }
}
